# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqOre5qVxsVOAaZ9XZBg6BtocwHyXrxx
"""

"""
Trabalho de Programação 2 - Disciplina: Banco de Dados
Aluno: João E. P. Garcia
RA: 277172
Prof. Dr. Trucíos
Descrição: Script para analisar atrasos de voos da American Airlines em 2015
           e gerar um calendário visual mostrando o percentual de voos atrasados por dia.

Observações:
- Dataset baixado do Kaggle. O arquivo original vinha em uma pasta zipada chamada 'archive',
  que foi renomeada para 'dados', seguindo a organização dos slides do prof Trucíos.
- No desafio, era opcional analisar apenas uma companhia aérea. Tomei a iniciativa
  de filtrar apenas a American Airlines (AA).
"""

# Importação das bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import calendar
from datetime import datetime
import matplotlib.colors as mcolors
import os
import zipfile

def main():
    # Lista de possíveis caminhos do arquivo zip que sera introduzida no diretorio para a analise ( coloquei isso pois achei q a importacao do dataset no diretorio poderia causar confusoes para diferentes usuarios)
    possible_paths = [
        'dados.zip',
        '../dados.zip',
        './dados/dados.zip',
        '../dados/dados.zip'
    ]

    file_path = None
    for path in possible_paths:
        if os.path.exists(path):
            file_path = path
            break

    chunksize = 100000        # Tamanho do pedaço para leitura em partes, meu computador conseguiu rodar isso com certa tranquilidade entao deixei assim
    airline = 'AA'            # Filtra apenas a American Airlines
    dtype_spec = {            # Garantir tipos de coluna corretos
        'ORIGIN_AIRPORT': str,
        'DESTINATION_AIRPORT': str,
        'CANCELLATION_REASON': str
    }

    daily_stats = {}          # Armazenar total de voos e atrasos por dia

    # Abrir arquivo zipado e extrair apenas o flights.csv
    with zipfile.ZipFile(file_path, 'r') as zip_ref:
        csv_file_path = zip_ref.extract('flights.csv')

    try:
        # Le o CSV em pedaços, filtra voos da AA em 2015 como solicitado
        for chunk in pd.read_csv(csv_file_path, chunksize=chunksize, dtype=dtype_spec, low_memory=False):
            chunk = chunk[chunk['AIRLINE'] == airline]
            chunk = chunk[chunk['YEAR'] == 2015]

            if chunk.empty:
                continue  # Pula pedaços sem dados (NA)

            # Converte atrasos para número e remove linhas inválidas
            chunk['ARRIVAL_DELAY'] = pd.to_numeric(chunk['ARRIVAL_DELAY'], errors='coerce')
            chunk = chunk.dropna(subset=['ARRIVAL_DELAY', 'YEAR', 'MONTH', 'DAY'])

            # Cria coluna com data completa e marca atrasos > 10 minutos
            chunk['DATE'] = pd.to_datetime(chunk[['YEAR', 'MONTH', 'DAY']])
            chunk['delayed'] = chunk['ARRIVAL_DELAY'] > 10

            # Agrupa por dia e soma atrasos e total de voos para eventualmente calcular a porcentagem
            daily_chunk = chunk.groupby('DATE').agg(
                total=('delayed', 'count'),
                delayed=('delayed', 'sum')
            )

            # Atualiza dicionário daily_stats ( atrasos dos voos )
            for date, row in daily_chunk.iterrows():
                date_key = date.date()
                if date_key not in daily_stats:
                    daily_stats[date_key] = {'total': 0, 'delayed': 0}
                daily_stats[date_key]['total'] += row['total']
                daily_stats[date_key]['delayed'] += row['delayed']

    finally:
        # Agora que a estatistica foi calculada, esse comando remove o arquivo temporário para nao demandar muito do computador
        if os.path.exists(csv_file_path):
            os.remove(csv_file_path)

    # Calcula percentual de atrasos por dia
    daily_percent = {}
    for date, stats in daily_stats.items():
        if stats['total'] > 0:
            daily_percent[date] = (stats['delayed'] / stats['total']) * 100
        else:
            daily_percent[date] = 0.0

    # Configurações de calendário e nomes em português(no slide estava em ingles mas deixarei em portugues para melhor compreensao)
    calendar.setfirstweekday(calendar.SUNDAY)
    meses_pt = {1: 'Janeiro', 2: 'Fevereiro', 3: 'Março', 4: 'Abril',
                5: 'Maio', 6: 'Junho', 7: 'Julho', 8: 'Agosto',
                9: 'Setembro', 10: 'Outubro', 11: 'Novembro', 12: 'Dezembro'}
    dias_semana_pt = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']

    # Cria figura e eixos para o calendário (3x4 meses)
    fig, axes = plt.subplots(3, 4, figsize=(15, 10))
    fig.suptitle(f'Percentual de Voos Atrasados - American Airlines (2015)', fontsize=16)
    cmap = plt.cm.YlOrRd
    max_percent = max(daily_percent.values()) if daily_percent else 100
    norm = mcolors.Normalize(vmin=0, vmax=max(100, max_percent))

    # Loop por cada mês para gerar heatmap pedido pelo prof
    for month in range(1, 13):
        ax = axes[(month-1)//4, (month-1)%4]
        month_cal = calendar.monthcalendar(2015, month)
        heatmap_data = np.full((6, 7), np.nan)  # Semanas x dias

        # Preenche matriz com percentuais
        for week_idx, week in enumerate(month_cal):
            for day_idx, day in enumerate(week):
                if day != 0:
                    current_date = datetime(2015, month, day).date()
                    heatmap_data[week_idx, day_idx] = daily_percent.get(current_date, 0)

        # Plota heatmap do mês
        im = ax.imshow(heatmap_data, cmap=cmap, norm=norm, aspect='auto')
        ax.set_title(meses_pt[month])
        ax.set_xticks(np.arange(7))
        ax.set_xticklabels(dias_semana_pt)
        ax.set_yticks([])

        # Adiciona valores dentro das células, as quais não aparecem como no calendario do slide, mas a IA me recomendou essa funcionadade e achei interessante
        for week_idx, week in enumerate(month_cal):
            for day_idx, day in enumerate(week):
                if day != 0:
                    current_date = datetime(2015, month, day).date()
                    value = daily_percent.get(current_date, 0)
                    text_color = 'white' if value > 50 else 'black'
                    ax.text(day_idx, week_idx, f'{value:.0f}', ha='center', va='center', color=text_color, fontsize=8)

    # Barra de cores ao lado do calendário ( escolhi uma paleta com cores mais quentes, achei mais bonito )
    cbar_ax = fig.add_axes([0.92, 0.15, 0.02, 0.7])
    cbar = fig.colorbar(im, cax=cbar_ax)
    cbar.set_label('Percentual de Atraso (%)', rotation=270, labelpad=20)

    # Salva figura e printa ela
    plt.savefig('calendario_atrasos_pt.png', dpi=300, bbox_inches='tight')
    plt.show()
    # calla a funcao para rodar o codigo
if __name__ == '__main__':
    main()